# Generated by Django 4.2.1 on 2023-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_user_name', models.CharField(max_length=50)),
                ('event_user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_createdby',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='event',
            name='event_participant',
            field=models.ManyToManyField(to='events.eventuser'),
        ),
    ]
